name: shell lint

on:
  push:
    branches:
      - master
    paths:
      - 'bash_completion'
      - '.shellcheckrc'
      - '.github/workflows/shellcheck.yml'

  pull_request:
    branches:
      - master
    paths:
      - 'bash_completion'
      - '.shellcheckrc'
      - '.github/workflows/shellcheck.yml'

  workflow_dispatch:

jobs:
  lint:
    name: Run shell linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install packages
        run: |
          sudo apt install shellcheck

      - name: Run shellcheck
        run: |
          shellcheck bash_completion
